import { spawnSync } from "node:child_process";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { afterEach, describe, expect, test } from "vitest";

const checker = resolve("scripts/check-version-consistency.mjs");
const fixtureRoots: string[] = [];

function writeJson(path: string, value: unknown) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, `${JSON.stringify(value, null, 2)}\n`);
}

function writeCargoPackage(root: string, version: string) {
  mkdirSync(join(root, "src"), { recursive: true });
  writeFileSync(join(root, "src", "lib.rs"), "pub fn fixture() {}\n");
  writeFileSync(
    join(root, "Cargo.toml"),
    `[package]\nname = "fixture"\nversion = "${version}"\nedition = "2021"\n`,
  );
  writeFileSync(
    join(root, "Cargo.lock"),
    `# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = "fixture"\nversion = "${version}"\n`,
  );
}

function writeFixture({
  packageVersion = "2.1.1",
  packageLockVersion = packageVersion,
  packageLockRootVersion = packageLockVersion,
  tauriVersion = packageVersion,
  cargoVersion = packageVersion,
} = {}) {
  const root = mkdtempSync(join(tmpdir(), "version-check-"));
  fixtureRoots.push(root);

  writeJson(join(root, "package.json"), { version: packageVersion });
  writeJson(join(root, "package-lock.json"), {
    version: packageLockVersion,
    packages: {
      "": { version: packageLockRootVersion },
    },
  });
  writeJson(join(root, "src-tauri", "tauri.conf.json"), { version: tauriVersion });
  writeCargoPackage(root, cargoVersion);

  return root;
}

function runChecker(root: string) {
  return spawnSync(process.execPath, [checker], {
    cwd: root,
    encoding: "utf8",
  });
}

describe("check-version-consistency", () => {
  afterEach(() => {
    while (fixtureRoots.length > 0) {
      rmSync(fixtureRoots.pop()!, { recursive: true, force: true });
    }
  });

  test("accepts aligned package, Tauri, and Cargo versions", () => {
    const root = writeFixture();
    const result = runChecker(root);

    expect(result.status).toBe(0);
    expect(result.stdout).toContain("Version metadata is consistent: 2.1.1");
  });

  test("rejects mismatched Tauri config version", () => {
    const root = writeFixture({ tauriVersion: "2.1.2" });
    const result = runChecker(root);

    expect(result.status).toBe(1);
    expect(result.stderr).toContain("Version metadata is inconsistent");
    expect(result.stderr).toContain("src-tauri/tauri.conf.json: 2.1.2");
  });

  test("rejects mismatched Cargo workspace package version", () => {
    const root = writeFixture({ cargoVersion: "2.1.0" });
    const result = runChecker(root);

    expect(result.status).toBe(1);
    expect(result.stderr).toContain("Version metadata is inconsistent");
    expect(result.stderr).toContain("Cargo package fixture: 2.1.0");
  });
});
